### ISSUE TITLE
Docker always tries to open port 3306?

### ISSUE THREAD

**Issue by mikewrighton** [openzipkin/docker-zipkin#123]
If I try to run Zipkin with the Cassandra backend as per the README:

`docker-compose -f docker-compose.yml -f docker-compose-cassandra.yml up`

I get the error `Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated`. This also happens when I try to run the UI. Seems like MySQL is the base storage type and so that port is always exposed? I can fix this by commenting out the line `- 3306:3306`.

**Comment by adriancole** [comment]
yeah this does. I suspect you are running native docker (as opposed to toolbox w/virtualbox) right? #108

**Comment by mikewrighton** [comment]
I'm running native docker on OS/X, yeah.

**Comment by adriancole** [comment]
so, we could remove the exposing of ports (or comment them out by default).
That would leave us with only exposing zipkin's which is unlikely to
conflict. By commenting out, as opposed to removing, we could say something
like..

# uncomment this to access the internal mysql used by zipkin

**Comment by mikewrighton** [comment]
Yeah I think removing the port mapping would be good, or maybe even removing all the MySQL stuff from the base file and just creating a `docker-compose-mysql.yml`, to avoid confusion?

**Comment by adriancole** [comment]
I think it would be better to just remove the port mapping :) otherwise the
base file isn't realistic (just in-memory and you can do that with java
-jar)
