### ISSUE TITLE
Error testing Zipkin with Kafka

### ISSUE THREAD

**Issue by sdiallo-talend** [openzipkin/docker-zipkin#131]
Hi,

When i use open zipkin and kafka, i got an error side zipkin collector, here is the stack trace, can someone face to the same issue ?

zipkin          | java.lang.IllegalArgumentException: Error reading Span from TBinary
zipkin          |       at zipkin.internal.ThriftCodec.exceptionReading(ThriftCodec.java:579) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.internal.ThriftCodec.read(ThriftCodec.java:508) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.internal.ThriftCodec.readSpan(ThriftCodec.java:74) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.collector.Collector.acceptSpans(Collector.java:107) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.collector.kafka.KafkaStreamProcessor.run(KafkaStreamProcessor.java:65) [zipkin-collector-kafka-1.20.0.jar!/:na]
zipkin          |       at zipkin.collector.kafka.KafkaCollector$LazyStreams.lambda$guardFailures$0(KafkaCollector.java:222) [zipkin-collector-kafka-1.20.0.jar!/:na]
zipkin          |       at zipkin.collector.kafka.KafkaCollector$LazyStreams$$Lambda$1.run(Unknown Source) [zipkin-collector-kafka-1.20.0.jar!/:na]
zipkin          |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
zipkin          |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
zipkin          |       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
zipkin          | Caused by: java.lang.NullPointerException: null
zipkin          |       at zipkin.Span.<init>(Span.java:163) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.Span$Builder.build(Span.java:374) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.internal.ThriftCodec$4.read(ThriftCodec.java:337) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.internal.ThriftCodec$4.read(ThriftCodec.java:290) ~[zipkin-1.20.0.jar!/:na]
zipkin          |       at zipkin.internal.ThriftCodec.read(ThriftCodec.java:506) ~[zipkin-1.20.0.jar!/:na]

**Comment by adriancole** [comment]
interesting.. looks like it couldn't read the trace id. how are you
serializing/reporting spans to kafka? Did this just recently break in 1.20
or has this never worked for you.

**Comment by sdiallo-talend** [comment]
Hi,

It's my first time to test openzipkin with kafka, i follow this tutorial for producing events: https://blog.codecentric.de/en/2016/04/event-driven-microservices-spring-cloud-stream/

And i use openzipkin for consuming events

**Comment by adriancole** [comment]
this is a known issue.. you can't receive spans issued by spring-cloud-stream over kafka with the basic zipkin server. you have to run https://github.com/spring-cloud/spring-cloud-sleuth/tree/master/spring-cloud-sleuth-zipkin-stream

Once https://github.com/spring-cloud/spring-cloud-sleuth/issues/253 is complete, you should be able to use normal zipkin for this.

**Comment by sdiallo-talend** [comment]
Thanks @adriancole
