### ISSUE TITLE
When testing variables in shell they should be double quoted

### ISSUE THREAD

**Issue by someword** [openzipkin/docker-zipkin#132]
The docker container ships with various profiles that are shell scripts.  In the shell scripts tests are being done on optional variables which is throwing errors because the optional variables are not double quoted.

Shell best practice is to double quote variables when comparing, testing, etc.

**Comment by someword** [comment]
Before the patch I get the following because we are testing a nil/null/nothing


> docker run -it -p 9411:9411 -e STORAGE_TYPE=elasticsearch -e ES_AWS_DOMAIN=your_domain -v $HOME/.aws:/root/.aws:ro openzipkin/zipkin
> sh: -z: unknown operand
> Elasticsearch domain: your_domain


After the patch no errors

> docker run -it -p 9411:9411 -e STORAGE_TYPE=elasticsearch -e ES_AWS_DOMAIN=your_domain -v $HOME/.aws:/root/.aws:ro openzipkin/zipkin
> Elasticsearch domain: your_domain

**Comment by adriancole** [comment]
thanks for the note. care to raise your commit as a PR?

**Comment by someword** [comment]
doh!  Fixed my PR to go against correct repo:)
