### ISSUE TITLE
Allow configuring zipkin URL for zipkin-ui image

### ISSUE THREAD

**Issue by Rurouni** [openzipkin/docker-zipkin#134]
At the moment in the zipkin-ui image nginx config has hardcoded  `http://zipkin:9411` https://github.com/openzipkin/docker-zipkin/blob/master/zipkin-ui/nginx.conf#L51
Works for compose  but won't work with kubernetes pod for example (it needs to be localhost there)

It would be great if this docker image allowed configuring ZIPKIN_HTTP_ENDPOINT env var
Thank you

**Comment by adriancole** [comment]
I think this will be fixable in tandem with a change in zipkin-ui. We just need a quorum on how this will be sent to the javascript

https://github.com/openzipkin/zipkin-ui/issues/25

**Comment by charlescui** [comment]
@Rurouni @adriancole it's easy, just pass env at you compile zipkin-ui.

Find keyword `baseUri` in zipkin-ui, in the content you could write some code like:

```js
@Injectable()
export class ZipkinService {
    traces: Trace[];
    baseUri: string;
    basePort: string;
    services: string[];

    constructor( @Inject(Http) private http: Http) {
        this.baseUri = process.env.ZIPKIN_HOST || 'localhost';
        this.basePort = process.env.ZIPKIN_PORT || '9411';
        this.traces = null;
    }

    getServices() {
        this
            .http
            .get(`http://${this.baseUri}:${this.basePort}/api/v1/services`, {})
            .subscribe(res => {
                this.services = <string[]>(res.json());
                this.services.push('[any]');
                this.services.sort();
            });
    }
```

just 2 files you should change:
```
➜  zipkin-ui git:(daily/1.2.0) ✗ ack baseUri
src/app/tracegraph/tracegraph.component.ts
12:    baseUri: string;
16:        this.baseUri = process.env.ZIPKIN_HOST || 'localhost';
24:            .get(`http://${this.baseUri}:${this.basePort}/api/v1/dependencies?endTs=1474206961061&lookback=86400000`, {})

src/app/zipkin/zipkin.ts
157:    baseUri: string;
162:        this.baseUri = process.env.ZIPKIN_HOST || 'localhost';
170:            .get(`http://${this.baseUri}:${this.basePort}/api/v1/services`, {})
184:        var uri = `http://${this.baseUri}:${this.basePort}/api/v1/traces?endTs=${endTs}&lookback=${lookback}&annotationQuery=&limit=${limit}&minDuration=${minDuration}&spanName=all`;
```

I will make a docker image for run in k8s.

**Comment by adriancole** [comment]
thanks for the offer to help. I think these changes will be

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-ui/issues/34 suggests separate env variables to assign this.. like `export ZIPKIN_HOST=172.16.10.56 ZIPKIN_PORT=32008` please give feedback if this works for you or not.

Personally, I like `ZIPKIN_HTTP_ENDPOINT` or similar better as this is less sensitive to people who might have an SSL endpoint or have mounted the zipkin api under /zipkin.

**Comment by charlescui** [comment]
@adriancole mount a url path is a good idear.I have mount ui at /zipkin with expressjs server and httpProxy serve it.

**Comment by adriancole** [comment]
Thanks for all the patience and the help

I re-pushed docker images for 1.22.1 including a now working zipkin-ui image!

<img width="917" alt="screen shot 2017-04-14 at 5 52 17 pm" src="https://cloud.githubusercontent.com/assets/64215/25040354/5ecbe898-213b-11e7-8567-b0f99b02118d.png">


cc @llinder @rogeralsing
