### ISSUE TITLE
After long run zipkin will not reply

### ISSUE THREAD

**Issue by mumutu** [openzipkin/docker-zipkin#136]
I am using the default configuration to start the image only expose the inner port with -p 9411:9411

and in every client use `AsyncReporter.builder(URLConnectionSender.create(url)).build());` and At the very beginning it worked well， but two weeks later the zipkin server would not reply  though the docker instance was still running

here is the `docker stats`：

CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O             BLOCK I/O           PIDS
17b6255c8518        0.08%               905.4 MiB / 3.703 GiB   23.87%              235 MB / 78.7 MB    142 MB / 0 B        0

it occured several times， at first I thought it was the low configuration of the pc to blame， but after move the instance to a new one this error still turn up 

。unfortunately I am still new to this，so am I missing some start configuration to fit the production environment?

**Comment by adriancole** [comment]
are you running zipkin against a storage backend (like mysql) or are you
leaving it default (in-memory)

if using in-memory (our testing option), zipkin will eventually run out of
memory <https://github.com/openzipkin/zipkin/issues/1528>.

**Comment by mumutu** [comment]
Yep I am using the in-memory storage. So even the used mem not reached limit mem , there still has a chance the server will down (docker stats showed the mem usage is still within the limits) ?
Whatever really thanks! I will use a mysql storage backend to fit the production environment!

**Comment by adriancole** [comment]
good point, so the memory that is in contention is that in the java process.
