### ISSUE TITLE
1.22 Docker builds failing

### ISSUE THREAD

**Issue by StephenWithPH** [openzipkin/docker-zipkin#137]
openzipkin / docker-zipkin is failing on Travis. [The logs](https://travis-ci.org/openzipkin/docker-zipkin/builds/218450822#L455), along with what I can see on https://quay.io/repository/openzipkin/zipkin, make me think that Quay's build trigger is not working.

We're excited to get our hands on the 1.22 container image.

**Comment by devinsba** [comment]
Trying to rebuild to see if Quay wasn't responding during the last build

**Comment by devinsba** [comment]
So looking at the build more, someone with quay.io access will most likely need to finish this build. 

cc @openzipkin/devops-tooling

**Comment by adriancole** [comment]
Honestly I don't know why a build-trigger on zipkin repo ended with a noop build on quay. I followed the RELEASE instructions for a manual build/publish and all good now. It wasn't automatic as I needed to manually run the build-trigger for the zipkin image. I commented out everything in release.sh before synchronizing tags, and that ran it.

**Comment by adriancole** [comment]
ps thanks for opening this! I'm not sure the next release will run, but there's a chance there was something off about this particular tag/image.. we'll see and re-open if it sticks

**Comment by adriancole** [comment]
had to manually run the build trigger on the zipkin image while the release tag was going ... it picked up and proceeded. https://quay.io/repository/openzipkin/zipkin?tab=builds

I'm wondering if the web hook is screwed up

**Comment by adriancole** [comment]
note the same thing happened for zipkin-dependencnies.. the build trigger didn't go

**Comment by adriancole** [comment]
I had to simplify the tag regex to `^tags/[0-9]+.*`.. now good
