### ISSUE TITLE
Elasticsearch Service on Amazon should work with iam_role from EC2 instance

### ISSUE THREAD

**Issue by georambo** [openzipkin/docker-zipkin#148]
It seems that elastic search service api is using the credentials from the /root/.aws mount volume for making api requests to AWS API.  We should be able to use the iam_role of the host EC2 machine to make the AWS API calls when aws credentials are missing.

$ docker run -d -p 9411:9411 \
  -e STORAGE_TYPE=elasticsearch -e ES_AWS_DOMAIN=your_domain \
  -v $HOME/.aws:/root/.aws:ro \
  openzipkin/zipkin

**Comment by devinsba** [comment]
It will, unless there are credentials there it will use the instance profile. The ES config uses the `DefaultAWSCredentialsProviderChain` which is documented here: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

**Comment by georambo** [comment]
Thanks for the quick reply Devin.

Sounds great, that is the option I want to use.

May I ask if the docker instance will automatically query the amazon metadata service using the instace profile of the ec2 host?

My ec2 box has role assigned that has access to the elastic domain.  I only get the zipkin service to get access properly when providing the aws key and secret.  The docker image should automatically have access to that same instance profile I believe.

Thanks for your help.

**Comment by devinsba** [comment]
My instances are deployed this way, I can confirm this works

**Comment by georambo** [comment]
- from my ec2 box, the following works fine, so access policy seems ok for my instance profile:
`aws es describe-elasticsearch-domain --domain-name tf-elastic-search --region us-east-1`
- I start docker instance as follows
`docker run -d -p 9411:9411 -e STORAGE_TYPE=elasticsearch -e ES_AWS_DOMAIN=tf-elastic-search  openzipkin/zipkin`

But when I go to zipkin server, i get the following error:

ERROR: cannot load service names: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://es.us-east-1.amazonaws.com/2015-01-01/es/domain/tf-elastic-search}

**Comment by adriancole** [comment]
next step on this would be to see if logging can show what the credential
chain sees, if anything. This could be zipkin regular logging or
elasticsearch's http debug.

https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md

**Comment by georambo** [comment]
Thanks for the suggestino Adrian, that's what I would like to do, but I dont know how to run the zipkin server with live logs, or how to send the logs to a file.  

I start zipkin with the following command
`docker run -d -p 9411:9411 -e STORAGE_TYPE=elasticsearch -e ES_AWS_DOMAIN=tf-elastic-search openzipkin/zipkin`

I've gone into the docker machine and see the following running process but cannot understand how to rerun in non-daemon mode

`/bin/sh -c test -n "$STORAGE_TYPE" && source .${STORAGE_TYPE}_profile;     test -n "$KAFKA_BOOTSTRAP_SERVERS" && JAVA_OPTS="${JAVA_OPTS} -Dloader.path=ka
    5 root       0:16 java -Djava.security.egd=file:/dev/./urandom -cp . org.springframework.boot.loader.PropertiesLauncher`

**Comment by georambo** [comment]
all good, worked problem with aws support, problem was with policy definition on aws.  Thanks for the help.
