### ISSUE TITLE
Docker cache

### ISSUE THREAD

**Issue by eirslett** [openzipkin/docker-zipkin#15]
http://thenewstack.io/understanding-the-docker-cache-for-faster-builds/

I think we need some way of busting the cache, so it's not using an old version of openzipkin when building. (In fact, my docker build didn't even clone openzipkin at all)

**Comment by abesto** [comment]
My first idea is doing the clone outside the `Dockerfile`. This comes with the benefit of being able to add `.git` to `.dockerignore`.

**Comment by adriancole** [comment]
Once we do releases, we wouldn't be building from source, and instead
letting the user choose snapshot or some pinned version from bintray. Does
this change anything?

**Comment by abesto** [comment]
Even in that case I'd prefer downloading on the host instead of in the container, to keep the images super lean. (Obviously the `git clone` will become a `wget` etc.)

**Comment by abesto** [comment]
Wait, no. In an ideal world we'd have automated builds, which means everything would be inside the containers, even the downloadings. In that case #16 is only a temporary thing to use while we build the docker containers from source.

**Comment by abesto** [comment]
While we build the docker images from source, this is fixed by #16. The proper long-term solution is tracked in #18, so I'm closing this issue.
