### ISSUE TITLE
Throwing Azure Event Hubs Collector to the mix

### ISSUE THREAD

**Issue by aliostad** [openzipkin/docker-zipkin#150]
Hi,

Been reviewing main zipkin `Dockerfile` and been evaluating how to proceed with throwing EventHub collector to the mix.

Currently zipkin assumes Kafka - perhaps since there has not been any other collector. Should we consider:

1. Making collector driven by commandline similar to storage. This means the binaries will grow and also a tad more brittle.
2. Make a fork and have two folders with a Dockerfile in each: zipkin-kafka and zipkin-eventhub.

I personally still prefer option 1 but wonder what you would think?

**Comment by adriancole** [comment]
hmm we already have a docker process for non-core transports, did you miss
this? https://github.com/openzipkin/docker-zipkin-azure

**Comment by aliostad** [comment]
I have - it prob happened while I was away. Sorry, closing again :/

**Comment by adriancole** [comment]
anyway thanks for being interested in this!
