### ISSUE TITLE
Provide an option to define logging.level.zipkin or generic extra arguments

### ISSUE THREAD

**Issue by asyd** [openzipkin/docker-zipkin#157]
I'm currently testing zipkin with the docker images, however I have an issue when sending a big json from aiozipkin client. So I want trying to understand what happens but there as far as I can tell there is no way to run the docker image in debugging mode (as https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#logging) . 

I tried to use JAVA_OPTS but it failed with `Unrecognized option` `Error: Could not create the Java Virtual Machine.`

I think adding ab extra environment variables to pass extra arguments to the main class could be a good idea!

Thanks!

**Comment by adriancole** [comment]
https://github.com/openzipkin/docker-zipkin/pull/158
