### ISSUE TITLE
Cassandra - '/cassandra/data' mounting issues

### ISSUE THREAD

**Issue by mclarke47** [openzipkin/docker-zipkin#164]
This is a strange one so I'll just write out the timeline of what happens and then discuss possible fixes.

1. The cassandra schema is loaded into the docker image when the image is built
2. Deploy zipkin to kubernetes with [zipkin-helm](https://github.com/Financial-Times/zipkin-helm) using cassandra3 storage, with the config flag `ENSURE_SCHEMA=true`
3. Mounting a [persistent volume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) over `/cassandra/data`. This deletes the schema installed by step 1
4. When the servers start up and runs ensure the schema they don't create the zipkin2.dependency (not sure why) table resulting in the UI not working

I was able to work around this by adding the line `cp -R /cassandra/data/ /cassandra/data-tmp/` after [this line](https://github.com/openzipkin/docker-zipkin/blob/master/cassandra/install.sh#L45).

Then `cp -rf /cassandra/data-tmp/* /cassandra/data/` [before cassandra starts](https://github.com/openzipkin/docker-zipkin/blob/master/cassandra/run.sh#L1)

This is obviously a bit hacky and would probably wipe out the traces when the pod restarts.

It think that there should be some way of persisting the `/cassandra/data` directory built by `docker build` if people want to mount persistent volumes like this.

**Comment by adriancole** [comment]
Sheesh had to get into the weeds to figure out this one huh?!
