### ISSUE TITLE
docker-swarm 

### ISSUE THREAD

**Issue by chengoldbond1** [openzipkin/docker-zipkin#168]
can you provide an explanation how to run zipkin on docker swarm?

**Comment by stanleegoodspeed** [comment]
@chengoldbond1 did you ever figure out how to run zipkin in swarm?

**Comment by zeagord** [comment]
Zipkin-server is a Java service and the docker images are published to the [docker hub](https://hub.docker.com/u/openzipkin/). 

You can run it in the docker swarm like you run any other service
