### ISSUE TITLE
It is not possible to use /bin/sh inside openzipkin/zipkin image

### ISSUE THREAD

**Issue by brempusz** [openzipkin/docker-zipkin#206]
Because final output image is based on `gcr.io/distroless/java:11-debug` it is not possible to use scripts like https://github.com/eficode/wait-for (or sh scripts) with this image; `/bin/` is empty (busybox stuff should be linked there). 

Use case: docker compose with zipkin + rabbit and `wait-for` used to check if rabbit is up before starting zipkin.

Quick (and dirty) workaround: change `wait-for` script to use `#!/busybox/sh` instead of `#!/bin/sh`.

**Comment by shakuzen** [comment]
What do you think @anuraaga?
