### ISSUE TITLE
How much memory to allocate ?

### ISSUE THREAD

**Issue by sebgoa** [openzipkin/docker-zipkin#209]
Hi,

Total zipkin newbie here. The docker image is used in kubernetes manifests of the knative project:

https://github.com/knative/serving/blob/master/config/monitoring/tracing/zipkin/100-zipkin.yaml

We are trying to set a memory request so that the pod can get scheduled if we have lower than 1 Gb available.

What would be a sane amount of memory to allocate to this container ?

thank you,

**Comment by adriancole** [comment]
#79 old but related so tagging. no need to look at it.

sorry I don't know for sure, but we have done some work on performance and overhead with elasticsearch recently. I recall doing a load test of 128 clients with 4 threads against the stock server and it is something in the couple hundreds of megs.

If you want to tune down the amount of heap, what I'd recommend is running prometheus and the grafana dashboard we have. Maybe start with 300MiB or so on the zipkin server. Then in your environment, you can look at or alert on heap related things as they are tracked with real usage.

In order buckle down is easier than unbuckling.

if you want to chat more, please join gitter https://gitter.im/openzipkin/zipkin

**Comment by sebgoa** [comment]
thank you
