### ISSUE TITLE
ERROR: cannot load remote service names: server error (Internal Server Error)

### ISSUE THREAD

**Issue by ordinary01** [openzipkin/docker-zipkin#216]
**docker-compose -f docker-compose.yml -f docker-compose-cassandra.yml up**
**_ERROR: cannot load remote service names: server error (Internal Server Error)_**

i find

**_host:9411/zipkin/api/v2/remoteServices?serviceName=all
500 Internal Server Error_**

**Comment by adriancole** [comment]
the url is strange as it shouldn't attempt to load names for service 'all's

can you try zipkin lens to see if same?

**Comment by adriancole** [comment]
fwiw I did the following and no error. maybe you can try latest pull?

```bash
docker-compose -f docker-compose.yml -f docker-compose-cassandra.yml pull
docker-compose -f docker-compose.yml -f docker-compose-cassandra.yml up
# then in another window
curl -s localhost:9411/zipkin/api/v2/remoteServices?serviceName=all
[]
```

**Comment by ordinary01** [comment]
thanks
