### ISSUE TITLE
Cassandra port not exposed to the host?

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [openzipkin/docker-zipkin#40]
Trying to connect directly to the cassandra image from the host I noticed the port was not exposed in the `docker-compose.yml` file, making the connection impossible (I might be wrong, docker newbie here).

Before I submit a 2 lines PR I was wondering if there was any specific reason not to do so.

**Comment by adriancole** [comment]
I don't think that was intentional :) go for it!

**Comment by jfeltesse-mdsol** [comment]
:ok: 

see PR #41
