### ISSUE TITLE
Remove travis-ci webhook

### ISSUE THREAD

**Issue by kristofa** [openzipkin/docker-zipkin#5]
I would like to remove the travis-ci webhook for docker-zipkin. There is no `.travis.yml` and I think it was not the intention to have a build on travis-ci?

Because of this webhook pull requests have a broken build indication. See #3 and #4 

wdyt @rtyler @eirslett ?

**Comment by rtyler** [comment]
@kristofa we *can*, I'd like to get some minimal set of validation that PRs are legit.

I'll disable it for now and file a ticket to readd it :)

**Comment by kristofa** [comment]
@rtyler that's a good idea. I agree that it would be good if we have a build that validates if the images can be build and that they work. A separate ticket to tackle this sounds good.

**Comment by rtyler** [comment]
nuked integration for now
