### ISSUE TITLE
Think about scheduled task

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-zipkin#75]
Both the spark job and any mysql backend need to have a periodic task run.  The spark job needs to be run in order to produce the dependency graph. The mysql backend needs to "delete from" in order to implement TTL. There's probably a simple pattern in docker nowadays we can use to implement both.

See https://github.com/openzipkin/zipkin/issues/792#issuecomment-160589617 from @MatMoore about needing TTL for MySQL
Also @prat0318 was asking about freshening the dependencies data from https://github.com/openzipkin/zipkin-dependencies-spark

cc @yurishkuro @jcarres-mdsol

**Comment by jcarres-mdsol** [comment]
Probably dependecies in mysql would need a job and a cached result in the DB.
I have ~9 milllion annotations and ~2 million spans and the dependencies api call times out.
The time to complete the query is quite lineal with the number of rows in the DB I've seen it growing from 2 secs steady till 20secs till eventually timeout now.

**Comment by adriancole** [comment]
Wrt mysql cache etc. Open an issue in OpenZipkin/zipkin? I'm unsurprised at
this, as the on demand query approach was more a 'starter kit'

**Comment by jcarres-mdsol** [comment]
Not suprised either. But if you are considering to run something to precreate dependencies for cassandra, maybe should also precreate them from mysql?

**Comment by adriancole** [comment]
Yeah, just this requires a job before you even start, which complicates
initial experience.

That said, it may be possible to use the same spark job for MySQL (which
you might guess I'd suggest we add an issue to zipkin-dependencies-spark)
in that case.

It may or may not be simpler, though. For example we may be able to do this
for MySQL without spark. That's why might be best to start an issue on the
topic first, then maybe move to a solution. Docker is the farthest point as
this is where we configure a solution.

**Comment by abesto** [comment]
Wrt. TTL in MySQL: not sure about a well-established pattern; some searching shows  that people usually just start up a container with `cron` as PID 1. Others include an infinite loop in their script. Others still wrap their script with an infinite loop in bash. Then there's the crazy stuff where they wrap cron with a python script for better logging.

I think for our purposes we can keep this simple and have a single bash script that takes care of TTL with a MySQL command run every minute or so, providing complete control over logging. For extra anti-fragile we can add `restart: always` to these containers in the `docker-compose.yml` to make sure the "cronjob" survives intermittent failures.

I assume the same would work for periodically running the spark job, but I have zero experience with spark.
