### ISSUE TITLE
Add image for zipkin-dependencies-spark

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-zipkin#76]
zipkin-dependencies-spark should be a daily scheduled task (#75)

https://bintray.com/openzipkin/maven/zipkin-dependencies-spark/1.25.3/view#files

**Comment by adriancole** [comment]
cc @yurishkuro @michaelsembwever @prat0318 @abesto

**Comment by abesto** [comment]
Slightly confused here. Daily? Did `docker-zipkin` go from "easy quick-stast" to "production-ready"?

**Comment by adriancole** [comment]
daily as in that's the granularity of the job data. For example, I leave my
test cluster up perpetually, and due to our lookback it will expire out in
7 days. daily isn't to be "production" mostly to keep it fresh and within
the correct interval of the job.

**Comment by abesto** [comment]
Gotcha. Thanks for the context.

**Comment by adriancole** [comment]
PS there's a bit of a trick to this, too.. Someone may want to run it on
demand as opposed to waiting until midnight or whatever. Ex. I do some
traveling generation and want to explicitly invoke the aggregation job.

Not sure the docker-compose way to do this and/or if this would be a better
alternative to cron.

**Comment by adriancole** [comment]
work in progress here https://github.com/openzipkin/docker-zipkin/pull/107

**Comment by adriancole** [comment]
@travisby @jcarres-mdsol @abesto @kristofa @klingerf almost ready to go on this. one thing we should explicitly decide is to whether to make the image here or a separate repo.

ex. the versions aren't aligned the dependencies job will be version 1.0, for example, and the code is fairly decoupled from zipkin.

We could still add the dependencies job to the compose file even if it doesn't live here, regardless.

thoughts?

**Comment by adriancole** [comment]
my 2p is that having the image here is easier, but "dirtier" conversely, having the image in a new repo docker-zipkin-dependencies is cleaner, but more administrative. Regardless, I do expect the dependencies job to have a different change cycle than the rest of zipkin, so more in favor of a separate repo (knowing there's a bit more setup needed).

**Comment by adriancole** [comment]
repurposing the old docker repo for java for dependencies, as it significantly reduces the work involved https://github.com/openzipkin/docker-zipkin-dependencies
