### ISSUE TITLE
Graceful shutdown of containers

### ISSUE THREAD

**Issue by skstronghold** [openzipkin/docker-zipkin#80]
Currently, Containers are not able to shutdown gracefully as the main process(`java -jar ...`) is not running as `pid 1`. Therefore, they are not able to receive signals sent to the container.

Recommended way would be to add `CMD` in exec form like `CMD ["run.sh"]` and run java process with `exec` to prevent forking of a new process i.e. replacing `java -jar ...` with `exec java -jar ...`

**Comment by adriancole** [comment]
Good idea!

wanna give that a try via a pull request? just make sure you try out the existing docker-compose file once finished.
