### ISSUE TITLE
Exception, due to Kafka version 

### ISSUE THREAD

**Issue by liuyan3514** [openzipkin/docker-zipkin#87]
I use kafka_0.8.2.2 server , Exception follows
kafka.consumer.ConsumerFetcherThread - [ConsumerFetcherThread-zipkin_zipkin-0-1], Error in fetch kafka.consumer.ConsumerFetcherThread$FetchRequest@7a949f14. Possible cause: java.nio.BufferUnderflowException

When i update version to 0.9.0.0, It's OK,

How to configure docker image for use kafka_0.8.2.2

**Comment by adriancole** [comment]
what version of zipkin are you running right now?

**Comment by liuyan3514** [comment]
zipkin version is 1.27.0
and our company's kafka is 0.8.1.1




来自 魅族 MX5

-------- 原始邮件 --------
发件人：Adrian Cole <notifications@github.com>
时间：周一 2月1日 17:13
收件人：openzipkin/docker-zipkin <docker-zipkin@noreply.github.com>
抄送：liuyan3514 <liuyan3514@sina.com>
主题：Re: [docker-zipkin] Exception, due to Kafka version  (#87)

**Comment by adriancole** [comment]
This was fixed in 1.30.0 most current version is 1.34.0
