### ISSUE TITLE
Link DockerHub repositories with GitHub

### ISSUE THREAD

**Issue by gena01** [openzipkin/docker-zipkin#89]
There's a couple of benefits for doing this:
1. README.md file(s) are pulled into the description.
2. Dockerfile used by the automation build is imported and updated in Docker Hub (Dockerfile tab)
3. There's a new link added from DockerHub to Github in order to find the github repo (source files)
4. Docker Hub can do the builds automatically based on tags/branches/regexp/etc.. and publish the images.

**Comment by adriancole** [comment]
Here's the most recent discussion on the topic #86 Mind having a look and sanity checking the idea with that in mind?

**Comment by abesto** [comment]
(And this is another repo I totally failed to "Watch". Fixed that now.)

Yeah, in theory I agree; in practice #86 describes pretty well why there's been no move yet. If this is mostly about documenting the state of things, that's also great input.

Another thing that's been discussed is exploding this "monorepo" into image-specific repositories, which may reduce the scope of this change by constraining each work item to a single image.

**Comment by adriancole** [comment]
one thing that came up recently is that quay remembered a bad download (cached). Without a busting strategy, only option is to bump the version. docker itself has a no-cache flag, which would obviate this. We could also somehow build something into our dockerfile to read a variable from Quay that busts the cache.

here's a related issue: https://github.com/moby/moby/issues/1326

I'm not sure if dockerhub is better or worse in this regard. Bad downloads are rare, but it did distract for a while.

**Comment by adriancole** [comment]
cc @dmitry-prokopchenkov who got bit by this on a stale zipkin-dependencies image

**Comment by anuraaga** [comment]
All the repos are linked now so think this issue is resolved (docker hub builds of release builds tracked in other issues)

**Comment by adriancole** [comment]
thanks for making such short work of this!
