### ISSUE TITLE
Getting lots of errors when using "docker-compose up"

### ISSUE THREAD

**Issue by jondunning** [openzipkin/docker-zipkin#9]
query_1     | [info] Loading project definition from /zipkin/project
web_1       | [info] Loading project definition from /zipkin/project
query_1     | [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
web_1       | [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
collector_1 | [info] Loading project definition from /zipkin/project
collector_1 | [warn] Multiple resolvers having different access mechanism configured with same name 'local'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
web_1       | [info] Set current project to zipkin (in build file:/zipkin/)
web_1       | [info] Set current project to zipkin-web (in build file:/zipkin/)
web_1       | [info] Writing build properties to: /zipkin/zipkin-web/target/resource_managed/main/com/twitter/zipkin/build.properties
web_1       | [warn] There may be incompatibilities among your library dependencies.
web_1       | [warn] Here are some of the libraries that were evicted:
web_1       | [warn] 	* com.github.spullara.mustache.java:compiler:0.8.12.1 -> 0.8.13
web_1       | [warn] 	* com.twitter.common:stats-util:0.0.42 -> 0.0.49
web_1       | [warn] Run 'evicted' to see detailed eviction warnings
web_1       | [info] Packaging /zipkin/zipkin-web/target/zipkin-web-1.2.0-SNAPSHOT.jar ...
web_1       | [info] Done packaging.
web_1       | [info] Running com.twitter.zipkin.web.Main -zipkin.web.query.dest=172.17.0.6:9411 -zipkin.web.rootUrl=DEFAULT_ROOTURL
web_1       | [error] Jul 22, 2015 7:56:33 AM com.twitter.finagle.http.HttpMuxer$$anonfun$5 apply
web_1       | [error] INFO: HttpMuxer[/stats.json] = com.twitter.finagle.stats.OstrichExporter(<function1>)
web_1       | [error] INF [20150722-07:56:34.236] web: /admin => com.twitter.server.handler.SummaryHandler
web_1       | [error] INF [20150722-07:56:34.238] web: /admin/server_info => com.twitter.finagle.Filter$$anon$2
web_1       | [error] INF [20150722-07:56:34.238] web: /admin/contention => com.twitter.finagle.Filter$$anon$2
web_1       | [error] INF [20150722-07:56:34.238] web: /admin/threads => com.twitter.finagle.Filter$$anon$2
web_1       | [error] INF [20150722-07:56:34.238] web: /admin/announcer => com.twitter.finagle.Filter$$anon$2
web_1       | [error] INF [20150722-07:56:34.239] web: /admin/dtab => com.twitter.finagle.Filter$$anon$2
web_1       | [error] INF [20150722-07:56:34.239] web: /admin/pprof/heap => com.twitter.server.handler.HeapResourceHandler
web_1       | [error] INF [20150722-07:56:34.239] web: /admin/pprof/profile => com.twitter.server.handler.ProfileResourceHandler
web_1       | [error] INF [20150722-07:56:34.239] web: /admin/pprof/contention => com.twitter.server.handler.ProfileResourceHandler
web_1       | [error] INF [20150722-07:56:34.240] web: /admin/ping => com.twitter.server.handler.ReplyHandler
web_1       | [error] INF [20150722-07:56:34.240] web: /admin/shutdown => com.twitter.server.handler.ShutdownHandler
web_1       | [error] INF [20150722-07:56:34.240] web: /admin/tracing => com.twitter.server.handler.TracingHandler
web_1       | [error] INF [20150722-07:56:34.240] web: /admin/logging => com.twitter.server.handler.LoggingHandler
web_1       | [error] INF [20150722-07:56:34.244] web: /admin/metrics => com.twitter.server.handler.MetricQueryHandler
web_1       | [error] INF [20150722-07:56:34.246] web: /admin/clients/ => com.twitter.server.handler.ClientRegistryHandler
web_1       | [error] INF [20150722-07:56:34.247] web: /admin/servers/ => com.twitter.server.handler.ServerRegistryHandler
web_1       | [error] INF [20150722-07:56:34.247] web: /admin/files/ => com.twitter.server.handler.ResourceHandler
web_1       | [error] INF [20150722-07:56:34.682] twitter: Finagle version 6.24.0 (rev=1e06db17ca2de4b85209dd2fbc18e635815e994b) built at 20141212-145625
web_1       | [error] INF [20150722-07:56:41.068] finagle: networkaddress.cache.ttl is not set, DNS cache refresh turned off
web_1       | [error] INF [20150722-07:56:41.630] tracing: Tracer: com.twitter.finagle.zipkin.thrift.SamplingTracer
query_1     | [info] Set current project to zipkin (in build file:/zipkin/)
query_1     | [info] Set current project to zipkin-query-service (in build file:/zipkin/)
collector_1 | [info] Set current project to zipkin (in build file:/zipkin/)
collector_1 | [info] Set current project to zipkin-collector-service (in build file:/zipkin/)
collector_1 | [info] Writing build properties to: /zipkin/zipkin-collector-service/target/resource_managed/main/com/twitter/zipkin/build.properties
collector_1 | [warn] There may be incompatibilities among your library dependencies.
collector_1 | [warn] Here are some of the libraries that were evicted:
collector_1 | [warn] 	* com.twitter.common.zookeeper:group:0.0.44 -> 0.0.78
collector_1 | [warn] Run 'evicted' to see detailed eviction warnings
collector_1 | [warn] There may be incompatibilities among your library dependencies.
collector_1 | [warn] Here are some of the libraries that were evicted:
collector_1 | [warn] 	* com.google.guava:guava:(11.0.2, 12.0.1, 14.0.1) -> 16.0.1
collector_1 | [warn] Run 'evicted' to see detailed eviction warnings
collector_1 | [warn] There may be incompatibilities among your library dependencies.
collector_1 | [warn] Here are some of the libraries that were evicted:
collector_1 | [warn] 	* junit:junit:(4.10, 3.8.1) -> 4.11
collector_1 | [warn] Run 'evicted' to see detailed eviction warnings
query_1     | [info] Writing build properties to: /zipkin/zipkin-query-service/target/resource_managed/main/com/twitter/zipkin/build.properties
query_1     | [info] Packaging /zipkin/zipkin-query-service/target/zipkin-query-service-1.2.0-SNAPSHOT.jar ...
query_1     | [info] Done packaging.
query_1     | [info] Running com.twitter.zipkin.query.Main -f zipkin-query-service/config/query-cassandra.scala
query_1     | [error] Jul 22, 2015 7:57:06 AM com.twitter.zipkin.query.Main$ main
query_1     | [error] INFO: Loading configuration
collector_1 | [info] Packaging /zipkin/zipkin-collector-service/target/zipkin-collector-service-1.2.0-SNAPSHOT.jar ...
collector_1 | [info] Done packaging.
collector_1 | [info] Running com.twitter.zipkin.collector.Main -f zipkin-collector-service/config/collector-cassandra.scala
collector_1 | [error] Jul 22, 2015 7:57:13 AM com.twitter.zipkin.collector.Main$ main
collector_1 | [error] INFO: Loading configuration
query_1     | [error] INF [20150722-07:57:26.636] stats: Starting LatchedStatsListener
query_1     | [error] DEB [20150722-07:57:26.712] nio: Using select timeout of 500
query_1     | [error] DEB [20150722-07:57:26.723] nio: Epoll-bug workaround enabled = false
query_1     | [error] 700 [20150722-07:57:26.810] net: HttpServer created http 0.0.0.0/0.0.0.0:9901
query_1     | [error] 700 [20150722-07:57:26.889] net: context created: /
query_1     | [error] 700 [20150722-07:57:26.900] net: context created: /report/
query_1     | [error] 700 [20150722-07:57:26.905] net: context created: /favicon.ico
query_1     | [error] 700 [20150722-07:57:26.910] net: context created: /static
query_1     | [error] 700 [20150722-07:57:26.919] net: context created: /pprof/heap
query_1     | [error] 700 [20150722-07:57:26.931] net: context created: /pprof/profile
query_1     | [error] 700 [20150722-07:57:26.932] net: context created: /pprof/contention
query_1     | [error] 700 [20150722-07:57:26.943] net: context created: /tracing
query_1     | [error] 700 [20150722-07:57:26.950] net: context created: /health
query_1     | [error] 700 [20150722-07:57:26.959] net: context created: /quitquitquit
query_1     | [error] 700 [20150722-07:57:26.960] net: context created: /abortabortabort
query_1     | [error] 700 [20150722-07:57:27.039] net: context created: /graph/
query_1     | [error] 700 [20150722-07:57:27.048] net: context created: /graph_data
query_1     | [error] INF [20150722-07:57:27.048] finagle: Finagle version 6.11.1 (rev=83de11a66b498351418433bcad00cbf4b7dc495c) built at 20140122-140039
query_1     | [error] INF [20150722-07:57:27.058] admin: Starting TimeSeriesCollector
query_1     | [error] INF [20150722-07:57:27.074] admin: Admin HTTP interface started on port 9901.
query_1     | [error] INF [20150722-07:57:28.063] cassie: Mapping cluster...
query_1     | [error] INF [20150722-07:57:28.240] query: Starting query thrift service on addr /0.0.0.0:9411
collector_1 | [info] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000f8080000, 59768832, 0) failed; error='Cannot allocate memory' (errno=12)
collector_1 | [info] #
collector_1 | [info] # There is insufficient memory for the Java Runtime Environment to continue.
collector_1 | [info] # Native memory allocation (malloc) failed to allocate 59768832 bytes for committing reserved memory.
collector_1 | [info] # An error report file with more information is saved as:
collector_1 | [info] # /zipkin/hs_err_pid83.log
collector_1 | java.lang.RuntimeException: Nonzero exit code returned from runner: 1
collector_1 | 	at scala.sys.package$.error(package.scala:27)
collector_1 | [trace] Stack trace suppressed: run last zipkin-collector-service/compile:run for the full output.
collector_1 | [error] (zipkin-collector-service/compile:run) Nonzero exit code returned from runner: 1
collector_1 | [error] Total time: 39 s, completed Jul 22, 2015 7:57:31 AM
query_1     | [error] DEB [20150722-07:57:32.529] cassie: Received: %s
deploy_collector_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping deploy_web_1...
Stopping deploy_query_1...
Stopping deploy_cassandra_1...

**Comment by eirslett** [comment]
It's complaining that the docker container doesn't get enough memory. Try giving it some more!
(Reducing Zipkin's memory footprint is a long-term goal)

**Comment by jondunning** [comment]
Gave it some more memory and now its booted up, should have read the debug first, need some more coffee :)

I do still have some errors though;

collector_1 | [error] INF [20150722-08:35:31.397] builder: Starting collector service on addr /0.0.0.0:9410
query_1     | [warn] there were 1 deprecation warning(s); re-run with -deprecation for details
query_1     | [warn] one warning found
query_1     | [info] Packaging /zipkin/zipkin-query-core/target/zipkin-query-core-1.2.0-SNAPSHOT.jar ...
query_1     | [info] Done packaging.
query_1     | [info] Packaging /zipkin/zipkin-query-service/target/zipkin-query-service-1.2.0-SNAPSHOT.jar ...
query_1     | [info] Done packaging.
query_1     | [info] Running com.twitter.zipkin.query.Main -f zipkin-query-service/config/query-cassandra.scala
query_1     | [error] Jul 22, 2015 8:35:36 AM com.twitter.zipkin.query.Main$ main
query_1     | [error] INFO: Loading configuration
query_1     | [error] SLF4J: Class path contains multiple SLF4J bindings.
query_1     | [error] SLF4J: Found binding in [jar:file:/root/.ivy2/cache/org.slf4j/slf4j-jdk14/jars/slf4j-jdk14-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
query_1     | [error] SLF4J: Found binding in [jar:file:/root/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
query_1     | [error] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
query_1     | [error] SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
query_1     | [error] INF [20150722-08:35:48.849] stats: Starting LatchedStatsListener
query_1     | [error] 700 [20150722-08:35:48.913] net: HttpServer created http 0.0.0.0/0.0.0.0:9901
query_1     | [error] 700 [20150722-08:35:48.930] net: context created: /
query_1     | [error] 700 [20150722-08:35:48.931] net: context created: /report/
query_1     | [error] 700 [20150722-08:35:48.933] net: context created: /favicon.ico
query_1     | [error] 700 [20150722-08:35:48.935] net: context created: /static
query_1     | [error] 700 [20150722-08:35:48.938] net: context created: /pprof/heap
query_1     | [error] 700 [20150722-08:35:48.944] net: context created: /pprof/profile
query_1     | [error] 700 [20150722-08:35:48.955] net: context created: /pprof/contention
query_1     | [error] 700 [20150722-08:35:48.963] net: context created: /tracing
query_1     | [error] 700 [20150722-08:35:48.964] net: context created: /health
query_1     | [error] 700 [20150722-08:35:48.964] net: context created: /quitquitquit
query_1     | [error] 700 [20150722-08:35:48.964] net: context created: /abortabortabort
query_1     | [error] 700 [20150722-08:35:48.979] net: context created: /graph/
query_1     | [error] 700 [20150722-08:35:48.980] net: context created: /graph_data
query_1     | [error] INF [20150722-08:35:48.981] admin: Starting TimeSeriesCollector
query_1     | [error] INF [20150722-08:35:48.993] admin: Admin HTTP interface started on port 9901.
query_1     | [error] DEB [20150722-08:35:49.414] twitter: LoadService: loaded instance of class com.twitter.finagle.stats.OstrichStatsReceiver for requested service com.twitter.finagle.stats.StatsReceiver
query_1     | [error] INF [20150722-08:35:49.459] twitter: Finagle version 6.24.0 (rev=1e06db17ca2de4b85209dd2fbc18e635815e994b) built at 20141212-145625
query_1     | [error] DEB [20150722-08:35:49.978] nio: Using select timeout of 500
query_1     | [error] DEB [20150722-08:35:49.979] nio: Epoll-bug workaround enabled = false
query_1     | [error] INF [20150722-08:35:50.136] cassie: Mapping cluster...
query_1     | [error] INF [20150722-08:35:50.184] query: Starting query thrift service on addr /0.0.0.0:9411
query_1     | [error] DEB [20150722-08:35:50.729] cassie: Received: %s
query_1     | [error] DEB [20150722-08:41:23.188] query: getServiceNames
query_1     | [error] DEB [20150722-08:41:23.241] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]], ColumnParent(column_family:ServiceNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
query_1     | [error] DEB [20150722-08:41:24.901] query: getSpanNames
query_1     | [error] DEB [20150722-08:41:24.906] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13]], ColumnParent(column_family:SpanNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
query_1     | [error] DEB [20150722-08:41:32.721] query: getServiceNames
query_1     | [error] DEB [20150722-08:41:32.723] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]], ColumnParent(column_family:ServiceNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
query_1     | [error] DEB [20150722-08:41:33.691] query: getSpanNames
query_1     | [error] DEB [20150722-08:41:33.711] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13]], ColumnParent(column_family:SpanNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
collector_1 | [error] INF [20150722-08:45:28.529] cassie: Mapping cluster...
query_1     | [error] INF [20150722-08:45:48.548] cassie: Mapping cluster...
query_1     | [error] DEB [20150722-08:45:48.584] cassie: Received: %s
query_1     | [error] DEB [20150722-08:45:58.047] query: getServiceNames
query_1     | [error] DEB [20150722-08:45:58.050] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]], ColumnParent(column_family:ServiceNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
query_1     | [error] DEB [20150722-08:45:58.761] query: getSpanNames
query_1     | [error] DEB [20150722-08:45:58.766] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13]], ColumnParent(column_family:SpanNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
query_1     | [error] DEB [20150722-08:46:01.151] query: getServiceNames
query_1     | [error] DEB [20150722-08:46:01.152] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16], java.nio.HeapByteBuffer[pos=0 lim=16 cap=16]], ColumnParent(column_family:ServiceNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)
query_1     | [error] DEB [20150722-08:46:02.144] query: getSpanNames
query_1     | [error] DEB [20150722-08:46:02.149] cassie: multiget_slice(Zipkin, [java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13], java.nio.HeapByteBuffer[pos=0 lim=13 cap=13]], ColumnParent(column_family:SpanNames), SlicePredicate(slice_range:SliceRange(start:, finish:, reversed:false, count:2147483647)), ONE)

**Comment by eirslett** [comment]
Do you get a similar error in the web interface? The query/collector backed by Cassandra is quite noisy, but often the application works anyways. The Cassandra code is being rewritten as we speak, so we just live with the pain until then. As long as it actually works, of course!

**Comment by jondunning** [comment]
No errors in the web interface so i will ignore these errors and proceed with my evaluation of zipkin. Thanks for your help.
