### ISSUE TITLE
dodge docker-assigned MYSQL_PORT variable

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-zipkin#94]
MYSQL_PORT is meaningful in zipkin, basically looking for what's likely port 3306

if you name a container mysql, docker will assign a variable like this: `MYSQL_PORT=tcp://172.17.0.82:3306`

Maybe we can make this smarter and automatically unset MYSQL_PORT if it has a non-numeric expression https://github.com/openzipkin/docker-zipkin/blob/master/base/.mysql_profile

**Comment by abesto** [comment]
* Environment variables like this are only set when using links in v1 (legacy / deprecated) `docker-compose.yml` files
 * The name of the variable is built from the alias, if it exists. For example `--link mysql:mysql_container` will set an environment variable `MYSQL_CONTAINER_PORT`.

Based on these, I'd prefer not introducing code to handle this case, but instead add a note to the README. Sound good?

**Comment by adriancole** [comment]
yep, if we choose to not handle it, we just need to adjust the
docker-compose examples to use a suffix like you mentioned. ex.
mysql_container

**Comment by abesto** [comment]
The only v1 docker-compose file is https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose-legacy.yml, which calls the mysql container `storage`, so I think we're good.

**Comment by adriancole** [comment]
this is the one that tripped the issue:
https://github.com/openzipkin/docker-zipkin/blob/master/docker-compose-mysql.yml#L13

**Comment by abesto** [comment]
But but but. https://docs.docker.com/compose/link-env-deprecated/ says "Environment variables will only be populated if you’re using the legacy version 1 Compose file format.". I'm confused, will reproduce.

**Comment by adriancole** [comment]
ahh.. actually I copied this, but maybe left out the version 2 thing.. will
verify!

**Comment by abesto** [comment]
On Docker `1.10.2, build c3959b1`, docker-compose `1.6.2, build 4d72027`, the env var is not set:

```
$ docker exec query env 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/java/jre/bin:/usr/local/java/bin
HOSTNAME=9024f5de4d16
STORAGE_TYPE=cassandra
TRANSPORT_TYPE=http
CASSANDRA_CONTACT_POINTS=cassandra
JAVA_HOME=/usr/local/java
JRE=/usr/local/java/jre
JAVA_OPTS=
ENV=/etc/shinit.sh
ZIPKIN_REPO=https://jcenter.bintray.com
ZIPKIN_VERSION=1.39.0
HOME=/root
```

**Comment by abesto** [comment]
Couldn't reproduce:

```
$ docker --version
Docker version 1.10.2, build c3959b1
$ docker-compose--version
docker-compose version 1.6.2, build 4d72027
$ docker exec query env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/java/jre/bin:/usr/local/java/bin
HOSTNAME=ee48fe35a81a
STORAGE_TYPE=mysql
TRANSPORT_TYPE=http
MYSQL_HOST=mysql
CASSANDRA_CONTACT_POINTS=cassandra
JAVA_HOME=/usr/local/java
JRE=/usr/local/java/jre
JAVA_OPTS=
ENV=/etc/shinit.sh
ZIPKIN_REPO=https://jcenter.bintray.com
ZIPKIN_VERSION=1.39.0
HOME=/root
```

**Comment by adriancole** [comment]
verified.. this is only an issue if using docker-compose version 1.

**Comment by adriancole** [comment]
thanks for looking into it!
