### ISSUE TITLE
fold in new code base

### ISSUE THREAD

**Issue by adriancole** [openzipkin/docker-zipkin#98]
Now that we've consolidated the zipkin code, it is time to tidy up docker. Here are the steps I think we should do:

* fold https://github.com/openzipkin/docker-zipkin-java into a directory called "zipkin" and remove base, collector and query
* rebase versions of the test images (mysql cassandra etc) to match zipkin (currently 1.1.3)
  * rationale: these are test images doesn't warrant the complexity of trying to deal with 2 versions.
* redirect docker-zipkin-java to here, similar to how we did https://github.com/openzipkin/zipkin-java

**Comment by adriancole** [comment]
cc @klingerf @kristofa @abesto @eirslett @gena01

**Comment by abesto** [comment]
Looks like a solid plan to me. Don't see downsides, especially since the main API users will use to access these images are the Docker repositories, so how we handle the changes there will be the more critical story.

**Comment by eirslett** [comment]
LGTM

**Comment by klingerf** [comment]
Yep, makes sense to me. Thanks for the heads up.

**Comment by adriancole** [comment]
pushing `release-1.1.4` to test things out. if anything fails I'll sort it.

**Comment by adriancole** [comment]
reset https://quay.io/repository/openzipkin/zipkin trigger to go to the docker-zipkin repo instead of docker-zipkin-java

**Comment by adriancole** [comment]
@kirktrue noticed you've a blog that mentions the former docker-zipkin-java repo. mind updating that?
